### ISSUE TITLE
Vault side kick init failing to startup as an init container

### ISSUE THREAD

**Issue by Hazrin84** [UKHomeOffice/vault-sidekick#95]
Hi, am noticing vault side kick fails to start up when used as an init container. See logs below. Appears to only happen on certain environments and has in the past been fixed by deleting and redeploying the service (multiple times).

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x764092]

goroutine 36 [running]:
main.VaultService.get(0x7fff91a574cd, 0x2c, 0xc42011f340, 0x0, 0x0, 0x0, 0xc420136020, 0x1, 0x1, 0xc4200646c0, ...)
	/home/travis/gopath/src/github.com/UKHomeOffice/vault-sidekick/vault.go:421 +0x13f2
main.(*VaultService).vaultServiceProcessor.func1(0xc420076780)
	/home/travis/gopath/src/github.com/UKHomeOffice/vault-sidekick/vault.go:152 +0x328
created by main.(*VaultService).vaultServiceProcessor
	/home/travis/gopath/src/github.com/UKHomeOffice/vault-sidekick/vault.go:113 +0x3f```

**Comment by james-bjss** [comment]
Hi @Hazrin84 as discussed this was caused by the vault client receiving a 404 with a nil response body.

Clearly a Segfault is not the appropriate behavior, so we would need to look at what the correct behavior should be under these circumstances. At the minimum it should be exiting with with a meaningful error.

**Comment by jg185347** [comment]
Hi @Hazrin84 are you able to find why you are getting this error? I am able to run side kick if I don't specify secrets to be mounted to the pod. If I add `- -cn=secret:secret/db/prod/username:file=.credentials`, this error will appear. I can be sure that the approle is granted permission to read the secret at this path, so I am suspecting the issue is with storing it into the path. Does anyone have an idea why this might be? 

This is my error message below. 
`I0630 20:07:30.802815       1 main.go:45] starting the vault-sidekick, v0.3.13 (git+sha 7836cf7)
I0630 20:07:30.803227       1 vault.go:289] rescheduling the resource: type: secret, path: secret/db/prod/username, channel: 0xc42004a7e0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7648e4]

goroutine 7 [running]:
main.VaultService.get(0xc4200165a0, 0x1c, 0xc4201073b0, 0x0, 0x0, 0x0, 0xc42000c088, 0x1, 0x1, 0xc42004a300, ...)
	/home/travis/gopath/src/github.com/UKHomeOffice/vault-sidekick/vault.go:422 +0x1434
main.(*VaultService).vaultServiceProcessor.func1(0xc42000e640)
	/home/travis/gopath/src/github.com/UKHomeOffice/vault-sidekick/vault.go:152 +0x328
created by main.(*VaultService).vaultServiceProcessor
	/home/travis/gopath/src/github.com/UKHomeOffice/vault-sidekick/vault.go:113 +0x3f
`
